[package]
name = "adif2json"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
adif-reader = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
