[workspace]
members = ["jelgen", "adif-reader"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["YÅ« KOBAYASHI <kb10uy@kb10uy.org>"]

[workspace.dependencies]
adif-reader = { path = "./adif-reader" }

regex = "1.12.2"
roxmltree = "0.21.1"
thiserror = "2.0.18"
