[package]
name = "schope"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mlua = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
