[package]
name = "adif-reader"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
regex = { workspace = true }
roxmltree = { workspace = true }
thiserror = { workspace = true }
unicode-segmentation = { workspace = true }
